server:
  port: 8091

spring:
  application:
    name: weiiboo-job-server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ae83db11-7015-425b-93b1-6bbc4341dce5

  profiles:
    active: druid
  datasource:
    notes:
      url: jdbc:mysql://localhost:3306/weber?useSSL=false&serverTimezone=UTC
      username: root
      password: 123abc
      driver-class-name: com.mysql.cj.jdbc.Driver
    user:
      url: jdbc:mysql://localhost:3306/weber?useSSL=false&serverTimezone=UTC
      username: root
      password: 123abc
      driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    database: 1
    host: 127.0.0.1
    port: 6379

# xxl配置信息
xxl:
  job:
    # 调度中心的地址，多个用逗号分隔，如 "http://localhost:8080/xxl-job-a
    admin:
      addresses: http://your-schedule-center-host:port/xxl-job-admin
    access-token: default_token
    executor:
      appname: test # 执行器的AppName，用于区分不同的执行器
      address: aa # 执行器的地址，调度中心会根据此地址去触发任务，可以是IP或者域名
      ip: aa  # 可选，执行器IP，若不设置则默认使用NetUtil.getLocalIp()
      port: 9999 # 执行器端口，默认为9999
      logpath: /data/applogs/xxl-job/ # 日志保存路径，需要手动创建
      logretentiondays: 30 # 日志保留天数，超出后自动清理