server:
  port: 8084

spring:
  profiles:
    active: druid
  datasource:
    url: jdbc:mysql://localhost:3306/weber?useSSL=false&serverTimezone=UTC
    username: root
    password: 123abc
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        max-active: 200   # 连接池最大连接数(负值表示没有限制)
        max-wait: -1   # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 10      # 连接池最大空闲连接
        min-idle: 0       # 连接池最小空闲连接
  data:
    # mongodb配置
    mongodb:
      host: localhost            # MongoDB 服务器地址
      port: 27017                # MongoDB 端口号
      database: weiiboo   # MongoDB 数据库名称

  # nacos配置
  application:
    name: weiboo-im-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ae83db11-7015-425b-93b1-6bbc4341dce5

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.weiiboo.modules.api.domin
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长

# rocketmq配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: weiiboo-note-server